name = "bakhryaan-blessed-playhouse"
version = "1.0.0"
type = "text"
production_host = "fuchsia-clownfish-vanna-oii6l24i.bls.dev"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "bakhryaan-blessed-playhouse_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "bakhryaan-blessed-playhouse.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeiccuy2khn7gyl6gdyuwnvu4mzibl4r7oumf6htiaabuv6ezmjbnkm"
created = "2025-08-25T11:42:25.944Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "e9f26639f9803d196add6424ee605c18d3dc7c8e248c66d7cc6f6b24a594aae5"
